CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Debugging & Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y

CONFIG_LOG=y
# Disable the direct RTT backend for logs
CONFIG_LOG_BACKEND_RTT=n

CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_RTT=y
# Direct logs to the shell backend instead
CONFIG_SHELL_LOG_BACKEND=y

# Device Drivers
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_ADC=y
CONFIG_SERIAL=y

# Power Management
#CONFIG_PM=y
#CONFIG_BOARD_ENABLE_DCDC=y

# Bluetooth LE
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_DEVICE_NAME="BLE-Tracker"
CONFIG_BT_BAS=y
CONFIG_BT_L2CAP_TX_MTU=64
CONFIG_BT_BUF_ACL_TX_SIZE=68

# Connection parameters
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=800
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=800
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y

CONFIG_MCUMGR_TRANSPORT_UART=n
#CONFIG_BT_DEBUG_MONITOR=n
# Optimization
CONFIG_FPU=y
